import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8f9fa",
    paddingHorizontal: 20,
    paddingTop: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#ff6b6b",
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#2d3436",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: "#636e72",
    textAlign: "center",
    marginBottom: 20,
  },
  formContainer: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#dfe6e9",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 12,
    backgroundColor: "#fff",
  },
  labelCategory: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2d3436",
    marginBottom: 8,
  },
  categoriesRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 15,
  },
  categoryBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  categoryText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#2d3436",
  },
  saveButton: {
    backgroundColor: "#0984e3",
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  listTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2d3436",
    marginBottom: 10,
  },
  listContainer: {
    paddingBottom: 20,
  },
  taskCard: {
    borderRadius: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 5,
    backgroundColor: "#fff",
    padding: 15,
    borderLeftWidth: 5,
    borderLeftColor: "#0984e3",
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2d3436",
  },
  taskCategory: {
    fontSize: 12,
    color: "#b2bec3",
    marginTop: 4,
  },
  badgePoints: {
    backgroundColor: "#ffeaa7",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  badgeText: {
    fontWeight: "bold",
    color: "#d63031",
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#636e72",
    textAlign: "center",
    marginTop: 20,
  },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  greeting: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#2d3436",
  },
  subGreeting: {
    fontSize: 13,
    color: "#636e72",
    marginTop: 2,
  },
  pointsBadge: {
    backgroundColor: "#ffeaa7",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "#fdcb6e",
    elevation: 4,
  },
  pointsText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#d63031",
  },
  parentAccessBtn: {
    alignSelf: "flex-end",
    marginBottom: 20,
    backgroundColor: "#dfe6e9",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 15,
  },
  parentAccessText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#636e72",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2d3436",
    marginBottom: 12,
  },

  taskInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  taskEmoji: {
    fontSize: 32,
    marginRight: 12,
  },
  taskTextContainer: {
    flex: 1,
  },
  taskReward: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ffffff",
    backgroundColor: "rgba(0, 0, 0, 0.15)",
    alignSelf: "flex-start",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginTop: 4,
  },
  actionButton: {
    backgroundColor: "#ffffff",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    elevation: 2,
  },
  actionButtonText: {
    fontWeight: "bold",
    color: "#0984e3",
    fontSize: 13,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
  },
  emptyEmoji: {
    fontSize: 50,
    marginBottom: 10,
  },
  emptySubText: {
    fontSize: 13,
    color: "#b2bec3",
    textAlign: "center",
    marginTop: 5,
    paddingHorizontal: 20,
  },
});
